Repository Unstoppable-Power/be19-1st-UP-WooGa, pull requests merged in 2025-07, with the labels that each got.

#6 fix: #5 - DB script DDL 쿼리 수정
  DDL/Wooga_DB_Script.sql
Labels: 오류 수정

#12 [feat] #10 폴더 구조 변경 및 더미 데이터(사용자, 관리자, 게시물, 카테고리) 추가
  DATA/sampleData.sql
  DDL/Wooga_DB_Script.sql
  DML/blackList/.gitkeep
  DML/category/.gitkeep
  DML/inquiry/.gitkeep
  DML/likePostList/.gitkeep
  DML/message/.gitkeep
  DML/post/.gitkeep
  DML/rental/.gitkeep
  DML/report/.gitkeep
  DML/user/.gitkeep
Labels: 기능 추가

#16 [feat] #14 - 일반 사용자 문의글 작성,수정,삭제,조회 기능 구현
  DML/inquiry/deleteInquiry.sql
  DML/inquiry/insertInquiry.sql
  DML/inquiry/selectInquiry.sql
  DML/inquiry/updateInquiry.sql
Labels: 문의

#25 [Feat] #13 - 일반 사용자 회원가입 구현
  DML/user/user_signup.sql
  DML/user/user_signup_trigger.sql
  TRIGGER/.gitkeep
Labels: 회원

#26 [feat] #11 - 게시물 생성, 수정, 삭제 기능
  DML/post/post_delete.sql
  DML/post/post_insert.sql
  DML/post/post_sample_data.sql
  DML/post/post_update.sql
  DML/post/postphoto_delete.sql
  DML/post/postphoto_insert.sql
  DML/post/postphoto_update.sql
Labels: 게시물
