Repository Unstoppable-Power/be19-1st-UP-WooGa, pull requests merged in 2025-08, with the labels that each got.

#40 [fix] #37 ddl문 일부 수정
  DDL/wooga_db_script.sql
Labels: 초기 세팅

#43 [Feat] #29 - 일반 사용자 수정, 탈퇴 기능 구현
  DDL/wooga_db_script.sql
  DML/user/user_info_update.sql
  DML/user/user_info_update_procedure.sql
  DML/user/user_info_update_trigger.sql
  DML/user/user_resign.sql
Labels: 회원

#46 [Feat] #30 - 관리자 계정 등록 및 회원 관리 기능 구현
  DML/admin/admin_auth.sql
  DML/admin/admin_user_monitoring.sql
Labels: 회원

#52 [Refact] #51 - 코드 구조 정리
  DATA/sample_data.sql
  DML/blackList/.gitkeep
  DML/inquiry/.gitkeep
  DML/message/.gitkeep
  DML/post/.gitkeep
  DML/post/post_management/post_sample_data.sql
  DML/rental/.gitkeep
  DML/rental/post_request_sample_data.sql
  DML/rental/rental_request/post_request_sample_data.sql
  DML/report/.gitkeep
  SETUP/PROCEDURE/category_delete_procedure.sql
  SETUP/PROCEDURE/inquiry_delete_procedure.sql
  SETUP/PROCEDURE/inquiryreply_insert_procedure.sql
  SETUP/PROCEDURE/reported_post_delete_procedure.sql
  SETUP/PROCEDURE/user_info_update_procedure.sql
  SETUP/PROCEDURE/user_signin_procedure.sql
  SETUP/SCHEDULER/blacklist_del_expired_date_event_schedular.sql
  SETUP/SCHEDULER/message_expire_event_schedular.sql
  SETUP/SCHEDULER/user_set_sleep_event_schedular.sql
  SETUP/TRIGGER/blacklist_set_black_count_trigger.sql
  SETUP/TRIGGER/user_info_update_trigger.sql
  SETUP/TRIGGER/user_signup_trigger.sql
  SETUP/set_event_scheduler_on.sql
Labels: 세팅

#54 [fix] #53 신고당한 게시물 조회시 신고 누적 횟수에 따른 내림차순 조회 및 PROCEDURE CALL 분리
  DML/category/category_delete.sql
  DML/post/reported_post/reported_post_delete.sql
  DML/post/reported_post/reported_post_select.sql
  DML/post/reported_post_select.sql
  SETUP/PROCEDURE/category_delete_procedure.sql
  SETUP/PROCEDURE/reported_post_delete_procedure.sql
Labels: 게시물, 신고/블랙리스트, 세팅

#66 [Refact] #60 - REQ-Q 문의 관리 기능 검토
  DML/inquiry/inquiry_delete.sql
  DML/inquiry/inquiry_insert.sql
  DML/inquiry/inquiry_select.sql
  DML/inquiry/inquiry_update.sql
  DML/inquiry/inquiryreply_insert.sql
  DML/inquiry/inquiryreply_manager_delete.sql
  DML/inquiry/inquiryreply_manager_update.sql
  DML/inquiry/inquiryreply_select.sql
  DML/inquiry/inquiryreply_user_delete.sql
  DML/inquiry/inquiryreply_user_update.sql
  images/req_gifs/REQ-Q-문의관리/REQ-Q-10_사용자문의답변수정.gif
  images/req_gifs/REQ-Q-문의관리/REQ-Q-11_문의답변조회.gif
  images/req_gifs/REQ-Q-문의관리/REQ-Q-1_문의글작성.gif
  images/req_gifs/REQ-Q-문의관리/REQ-Q-2_문의글삭제.gif
  images/req_gifs/REQ-Q-문의관리/REQ-Q-3_문의글수정.gif
  images/req_gifs/REQ-Q-문의관리/REQ-Q-4_문의글조회.gif
  images/req_gifs/REQ-Q-문의관리/REQ-Q-5,8_문의답변작성.gif
  images/req_gifs/REQ-Q-문의관리/REQ-Q-6_관리자문의답변삭제.gif
  images/req_gifs/REQ-Q-문의관리/REQ-Q-7_관리자문의답변수정.gif
  images/req_gifs/REQ-Q-문의관리/REQ-Q-9_사용자문의답변삭제.gif
Labels: 문의
